export const ERROR_CODES = {
  ACTUATOR_CACHE_NOT_FOUND: 'ACTUATOR_CACHE_NOT_FOUND',
  ACTUATOR_CACHE_TIMEOUT: 'ACTUATOR_CACHE_TIMEOUT',
  ACTUATOR_CACHE_UNAVAILABLE: 'ACTUATOR_CACHE_UNAVAILABLE',
  ACTUATOR_CONTRACT_INVALID: 'ACTUATOR_CONTRACT_INVALID',
  ACTUATOR_TOO_LARGE: 'ACTUATOR_TOO_LARGE',
  DATAPOOL_CONTRACT_INVALID: 'DATAPOOL_CONTRACT_INVALID',
  DATAPOOL_DATA_STALE: 'DATAPOOL_DATA_STALE',
  DATAPOOL_UNAVAILABLE: 'DATAPOOL_UNAVAILABLE',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  FARM_NOT_FOUND: 'FARM_NOT_FOUND',
  INVALID_REQUEST: 'INVALID_REQUEST',
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',
  EXCEL_GENERATION_FAILED: 'EXCEL_GENERATION_FAILED',
  REPORT_EXPIRED: 'REPORT_EXPIRED',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_NOT_READY: 'REPORT_NOT_READY',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
